Update model stub default crops
area17/twill pull request #1027
Opened 2021-06-30 21:06 UTC by pboi20

## Description

Small update to `model.stub` to use `default` instead of `desktop` as first crop name. This makes generated models compatible out of the box with the various methods from `HasMedias` that use `default` as implicit crop name.

## Related Issues

Fixes https://github.com/area17/twill/issues/604

2021-06-30 21:48 UTC, ifox requested changes
Definitely a welcome change for newcomers. I even wonder if it's too opinionated to ship that whole configuration by default, but that's another consideration.

2021-06-30 21:48 UTC, ifox commented on src/Commands/stubs/model.stub
>                      'name' => 'desktop',
```suggestion
                    'name' => 'default',
```

2021-06-30 21:58 UTC, pboi20 commented
@ifox That's a good point! I personally enjoy when generated code is closer to a full example than to a simple skeleton. But looking at `flexible` here, I see how it can be confusing for someone who has yet to explore more elaborate crop configurations.

2021-07-02 10:57 UTC, ifox approved these changes

2021-07-02 10:57 UTC, merged