Add `--factory` and `--seeder` to `twill:make:module`
area17/twill pull request #2402
Opened 2024-01-11 21:02 UTC by driftingly

## Description

This PR adds two new flags to the `twill:make:module` command:
- `--factory`
- `--seeder`

I'm not sure `--seeder` is worth keeping around, but I do think there is value in providing the option to create a factory when creating a module.

2024-01-11 21:14 UTC, ifox commented
Hi @driftingly thanks for your contributions! Excited to release Twill 3.1 with some of them next week!

This is a great addition to the CLI! Could we add capsules compatibility for the factory class to live within the capsule directory? The capsule generator already generates a seeder.

2024-01-11 22:54 UTC, ifox requested changes

2024-01-11 22:54 UTC, ifox commented on src/Commands/ModuleMake.php
> +            $activeModelTraitsString = Str::of($activeModelTraitsString)->replace(';',', HasFactory;');
```suggestion
            $activeModelTraitsString = Str::of($activeModelTraitsString)->replace(';', ', HasFactory;');
```

2024-01-11 22:54 UTC, ifox commented on src/Commands/ModuleMake.php
> +            Artisan::call('make:factory', ['name' => $modelName.'Factory','--model' => $modelClassName], $this->output);
```suggestion
            Artisan::call('make:factory', ['name' => $modelName . 'Factory', '--model' => $modelClassName], $this->output);
```

2024-01-11 22:54 UTC, ifox commented on src/Commands/ModuleMake.php
> +            Artisan::call('make:seeder '.$modelName.'Seeder', [], $this->output);
```suggestion
            Artisan::call('make:seeder ' . $modelName . 'Seeder', [], $this->output);
```

2024-01-12 00:36 UTC, driftingly commented
Hi @ifox Thanks for reviewing so quickly 🚀 
I updated the capsule generator to be compatible with the changes I made to the parent.
I didn't see where it already generates seeders.  If you could show me where I'll update the commands as needed, maybe I'll use the capsule code.

2024-01-12 01:22 UTC, ifox commented
Here's where the seeder is generated for capsules: https://github.com/area17/twill/blob/3.x/src%2FCommands%2FModuleMake.php#L315

2024-01-14 12:30 UTC, ifox commented
Nice, thanks!

I'm ok with that change, except for the case of singletons. When generating a singleton we do want the seeder to be generated by default because it is automatically called when browsing to that singleton in Twill, to create the single record.

2024-01-14 15:29 UTC, driftingly commented
No problem, I’ll update that.

2024-01-16 04:41 UTC, driftingly commented
@ifox OK - should be good now.

2024-01-18 00:03 UTC, ifox approved these changes

2024-01-18 00:06 UTC, merged