Multiple Block Editors
area17/twill pull request #918
Opened 2021-05-20 17:56 UTC by ptrckvzn

## Description

This PR integrates the frontend work of #112, rebased on the `2.x` branch.

It adds a migration to the table `blocks` in order to persist the "named" blocks in the database and retrieve them correctly both in the admin form and on the frontend with the introduction of a new function `renderNamedBlocks('fantastic-name', ...)`.

Multiple blocks editor are defined with the `name` key on the `@formField` statement in the module's form.

```php
// Use 'default' block name (compatible with previous block editor)
@formField('block_editor', [
  'type' => ['text', 'image', 'accordion'],
]);

// Use a named block editor
@formField('block_editor', [
  'name' => 'fantastic-name',
  'type' => ['text', 'image', 'accordion'],
]);
```

On the frontend, you can retrieve and output the blocks with:

```php
// Render 'default' or null blocks
{!! $item->renderBlocks(); !!}

// Render 'fantastic-name' blocks
{!! $item->renderNamedBlocks('fantastic-name'); !!}
```

## Related Issues

Rebase of #112.

2021-05-21 02:02 UTC, ifox requested changes
Awesome work @ptrckvzn, thanks for submitting! I've added a few comments and will test this out in the next few days.

2021-05-26 12:14 UTC, idflood commented
Awesome news : )

Now I'm wondering if these changes would make the whole "blocks" translatable? Currently it's only possible to [translate inner block](https://github.com/area17/twill/issues/204) fields, but for most of my websites the blocks could be different between languages.

I totally understand if it would still not be possible, but since there is a lot of refactoring going on here maybe a small change now would make translatable blocks "easy" to implement in the future.

2021-06-08 21:48 UTC, ptrckvzn commented on frontend/js/components/Dropdown.vue
> +          'overflow-y': this.maxHeight > 0 ? 'auto' : ''
This isn't necessary anymore I believe, so undoing the change.

2021-09-01 00:16 UTC, merged

2021-09-11 10:53 UTC, ifox commented
Hi @agnonym, you're totally right. I updated the mapping [here](https://github.com/area17/twill/commit/397792cafec7a43ec732ea22c9d1d3fa46b8e5f3) before releasing it for backward compatibility. In Twill 3.0 we will do some cleanup and realignment of the form fields options naming, but for now, I had to do this to avoid weird results.

2021-09-11 10:58 UTC, ifox commented
I updated @ptrckvzn's description to reflect that change:

```
@formField('block_editor', [
  'name' => 'fantastic-name',
  'title' => 'Fantastic name', // title to display in the Editor dropdown selector
  'label' => 'Add fantastic content', // custom trigger label
  'blocks' => ['text', 'image', 'accordion'],
]);
```